apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthsync-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/api/patients/(.*) /$1 break;
spec:
  rules:
    - http:
        paths:
          - path: /api/patients
            pathType: Prefix
            backend:
              service:
                name: patient-service
                port:
                  number: 80
