apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  uri: bW9uZ29kYitzcnY6Ly91c2VyOmFzZGZhc2RmQGhlYWx0aHN5bmMuNmlxOXcubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPWhlYWx0aHN5bmMtcGF0aWVudC1kYg==
